language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      env: TOX_ENV=lint
      install: pip install --upgrade flake8
      script: make test-lint
    - python: 3.7
      dist: xenial
      env: TOX_ENV=static-type-checks
      install:
        - pip install --upgrade mypy
        - pip install -r requirements.txt
      script: make test-type-check
    - python: 3.7
      dist: xenial
      env: TOX_ENV=coverage
      install:
        - pip install --upgrade coverage pytest
        - pip install .
      script:
        - make test-coverage
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - python: 3.6
      env: TOX_ENV=py36
      install: pip install --upgrade tox pytest
      script: tox -e $TOX_ENV
    - python: 3.7
      env: TOX_ENV=py37
      install: pip install --upgrade tox pytest
      dist: xenial
      script: tox -e $TOX_ENV
    - python: 3.8
      env: TOX_ENV=py38
      install: pip install --upgrade tox pytest
      dist: xenial
      script: tox -e $TOX_ENV
    - os: osx
      language: generic
      osx_image: xcode12 # Python 3.7.5 running on macOS 10.15.5
      install: pip3 install --upgrade tox pytest
      env: TOX_ENV=py37
      script: tox -e $TOX_ENV

# The following prevents Travis from running CI on pull requests that come from a
# branch in the same repository. Without this, it will run the same CI for the
# pull request branch _and_ the pull request itself, which makes no sense.
branches:
  only:
    - master
    # We want to build wip/* branches since these are not usually used for PRs
    - /^wip\/.*$/
    # We want to build version tags as well.
    - /^v\d+\.\d+.*$/

notifications:
  email: false
